# These are supported funding model platforms

github: daimor
patreon: 
open_collective: # Replace with a single Open Collective username
ko_fi: daimor
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
custom: https://liberapay.com/daimor/donate
