name: CI

on: [push,release]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@master
    - name: Start xvfb
      if: runner.os == 'Linux'
      run: |
        set -e
        /usr/bin/Xvfb :10 -ac >> /tmp/Xvfb.out 2>&1 &
        disown -ar
    - name: Use Node.js
      uses: actions/setup-node@master
      with:
        version: 10
    - run: npm install
    - run: npm run compile
    - run: npm run test
      env:
        DISPLAY: :10
    - name: Build package
      if: runner.os == 'Linux'
      run: |
        mkdir dist
        ./node_modules/.bin/vsce package -o ./dist/$(jq -r '.name + "-" + .version' package.json).vsix
    - uses: actions/upload-artifact@master
      if: runner.os == 'Linux'
      with:
        name: vscode-objectscript
        path: dist
